# Generated by Django 5.1.7 on 2025-03-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='genus',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='plant',
            name='soil_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
