# Generated by Django 5.1.7 on 2025-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_plant_description_alter_plant_genus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('genus', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('soil_type', models.CharField(blank=True, max_length=255)),
                ('watering_info', models.TextField(blank=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
